// src/components/Login.tsx
import React, { useState } from 'react';

function Login({ onLogin }: { onLogin: () => void }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Hardcoded demo account
    if ((username === 'user' && password === 'password') || (username === 'demo' && password === 'demo')) {
      onLogin();
    } else {
      alert('Invalid credentials');
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-900">
      <form onSubmit={handleSubmit} className="bg-gray-800 p-6 rounded shadow-md">
        <h2 className="text-2xl font-bold mb-4 text-orange-500">Login</h2>
        <input
          type="text"
          placeholder="Username"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          className="block w-full p-2 mb-4 border rounded bg-gray-700 text-white"
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className="block w-full p-2 mb-4 border rounded bg-gray-700 text-white"
        />
        <button type="submit" className="w-full bg-orange-500 text-white p-2 rounded">
          Login
        </button>
      </form>
    </div>
  );
}

export default Login;

// pages/auth/login.vue
<template>
  <div class="min-h-[80vh] flex items-center justify-center">
    <div class="bg-secondary-light p-8 rounded-lg w-full max-w-md">
      <h1 class="text-2xl font-bold mb-6 text-center">Login to FlameHost</h1>
      
      <form @submit.prevent="handleLogin" class="space-y-4">
        <div>
          <label class="block text-sm font-medium mb-2">Email</label>
          <input
            type="email"
            v-model="email"
            required
            class="w-full px-4 py-2 rounded-lg bg-secondary border border-gray-700 focus:border-primary outline-none"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium mb-2">Password</label>
          <input
            type="password"
            v-model="password"
            required
            class="w-full px-4 py-2 rounded-lg bg-secondary border border-gray-700 focus:border-primary outline-none"
          />
        </div>
        
        <button
          type="submit"
          class="w-full bg-primary hover:bg-primary-dark py-2 rounded-lg font-semibold transition-colors"
        >
          Login
        </button>
      </form>
      
      <p class="mt-4 text-center text-gray-400">
        Don't have an account?
        <NuxtLink to="/auth/register" class="text-primary hover:text-primary-dark">
          Register here
        </NuxtLink>
      </p>
    </div>
  </div>
</template>

<script setup>
const client = useSupabaseClient()
const router = useRouter()

const email = ref('')
const password = ref('')

const handleLogin = async () => {
  try {
    const { error } = await client.auth.signInWithPassword({
      email: email.value,
      password: password.value
    })
    
    if (error) throw error
    
    router.push('/dashboard')
  } catch (error) {
    console.error('Login error:', error.message)
    // Show error toast
  }
}
</script>
